import { ArtifactDefinition } from './types';

export const essenceArtifacts: Record<string, ArtifactDefinition> = {
  essence_lust: {
    id: 'essence_lust',
    name: 'Essence of Lust',
    nameKo: '정욕의 유물',
    type: 'stackable',
    description: 'Increases Power slightly.',
    descriptionKo: '채굴 위력이 미세하게 증가합니다.',
    image: 'LustEssence',
    bonus: { stat: 'power', value: 0.5 },
  },
  essence_gluttony: {
    id: 'essence_gluttony',
    name: 'Essence of Gluttony',
    nameKo: '폭식의 유물',
    type: 'stackable',
    description: 'Increases Max HP.',
    descriptionKo: '최대 체력이 증가합니다.',
    image: 'GluttoyEssence',
    bonus: { stat: 'maxHp', value: 5.0 },
  },
  essence_greed: {
    id: 'essence_greed',
    name: 'Essence of Greed',
    nameKo: '탐욕의 유물',
    type: 'stackable',
    description: 'Increases Luck slightly.',
    descriptionKo: '행운이 극히 미세하게 증가합니다.',
    image: 'GreedEssence',
    bonus: { stat: 'luck', value: 0.05 },
  },
  essence_wrath: {
    id: 'essence_wrath',
    name: 'Essence of Wrath',
    nameKo: '분노의 유물',
    type: 'stackable',
    description: 'Increases Critical Damage.',
    descriptionKo: '치명타 피해량이 증가합니다.',
    image: 'WrathEssence',
    bonus: { stat: 'critDamage', value: 0.01 },
  },
  essence_heresy: {
    id: 'essence_heresy',
    name: 'Essence of Heresy',
    nameKo: '이단의 유물',
    type: 'stackable',
    description: 'Increases Mining Speed.',
    descriptionKo: '채굴 속도가 미세하게 증가합니다.',
    image: 'HeresyEssence',
    bonus: { stat: 'miningSpeed', value: 0.005 },
  },
  essence_violence: {
    id: 'essence_violence',
    name: 'Essence of Violence',
    nameKo: '폭력의 유물',
    type: 'stackable',
    description: 'Increases Critical Rate.',
    descriptionKo: '치명타 확률이 미세하게 증가합니다.',
    image: 'ViolenceEssence',
    bonus: { stat: 'critRate', value: 0.001 },
  },
  essence_fraud: {
    id: 'essence_fraud',
    name: 'Essence of Fraud',
    nameKo: '기만의 유물',
    type: 'stackable',
    description: 'Increases Movement Speed.',
    descriptionKo: '이동 속도가 증가합니다.',
    image: 'FraudEssence',
    bonus: { stat: 'moveSpeed', value: 0.2 },
  },
  essence_treachery: {
    id: 'essence_treachery',
    name: 'Essence of Treachery',
    nameKo: '배신의 유물',
    type: 'stackable',
    description: 'Increases Defense.',
    descriptionKo: '방어력이 증가합니다.',
    image: 'TreacheryEssence',
    bonus: { stat: 'defense', value: 0.5 },
  },
};
