import { ArtifactDefinition } from './types';

export const relicArtifacts: Record<string, ArtifactDefinition> = {
  relic_asmodeus_ring: {
    id: 'relic_asmodeus_ring',
    name: "Asmodeus's Ring",
    nameKo: '아스모데우스의 반지',
    type: 'stackable',
    image: 'AsmodeusRingRelic',
    description: 'Increases EXP gain slightly per stack.',
    descriptionKo: '보유량에 따라 처치 시 획득 경험치(EXP)가 중첩 증가합니다.',
    bonus: { stat: 'critRate', value: 0.002 },
    effectId: 'EXP_BOOST',
    effectDescription: 'Increases EXP gain',
    effectDescriptionKo: '경험치 획득량 증가',
  },
  relic_beelzebub_needle: {
    id: 'relic_beelzebub_needle',
    name: "Beelzebub's Needle",
    nameKo: '벨제붑의 독니',
    type: 'stackable',
    image: 'BeelzebubNeedleRelic',
    description: 'Heals HP on kill per stack.',
    descriptionKo: '몬스터 처치 시 체력이 회복됩니다. (중첩 가능)',
    bonus: { stat: 'maxHp', value: 10 },
    effectId: 'LIFE_STEAL_PERCENT',
    effectDescription: 'HP Recovery on Kill',
    effectDescriptionKo: '처치 시 HP 회복',
  },
  relic_mammon_coin: {
    id: 'relic_mammon_coin',
    name: "Mammon's Golden Coin",
    nameKo: '마몬의 황금 주화',
    type: 'stackable',
    image: 'MammonCoinRelic',
    description: 'Increases gold from minerals per stack.',
    descriptionKo: '광물 판매 가격이 중첩 증가합니다.',
    bonus: { stat: 'luck', value: 0.2 },
    effectId: 'GOLD_SELL_BOOST',
    effectDescription: 'Increases Mineral Sell Price',
    effectDescriptionKo: '광물 판매가 증가',
  },
  relic_satan_heart: {
    id: 'relic_satan_heart',
    name: "Satan's Burning Heart",
    nameKo: '사탄의 타오르는 심장',
    type: 'stackable',
    image: 'SatanHeartRelic',
    description: 'Increases mining speed per stack.',
    descriptionKo: '기본 채굴 속도가 중첩 증가합니다.',
    bonus: { stat: 'miningSpeed', value: 0.05 },
    effectId: 'MINING_SPEED_BOOST',
    effectDescription: 'Increases Mining Speed',
    effectDescriptionKo: '채굴 속도 증가',
  },
  relic_belphegor_eye: {
    id: 'relic_belphegor_eye',
    name: "Belphegor's Shadow Eye",
    nameKo: '벨페고르의 눈',
    type: 'stackable',
    image: 'BelphegorEyeRelic',
    description: 'Increases mastery gain speed per stack.',
    descriptionKo: '모든 숙련도 획득 속도가 중첩 증가합니다.',
    bonus: { stat: 'power', value: 5 },
    effectId: 'MASTERY_BOOST',
    effectDescription: 'Increases Mastery Gain Speed',
    effectDescriptionKo: '숙련도 획득 속도 증가',
  },
  relic_abaddon_blade: {
    id: 'relic_abaddon_blade',
    name: "Abaddon's Broken Blade",
    nameKo: '아바돈의 부러진 칼날',
    type: 'stackable',
    image: 'AbaddonBladeRelic',
    description: 'Increases loot amount per stack.',
    descriptionKo: '몬스터 처치 시 전리품 획득량이 중첩 증가합니다.',
    bonus: { stat: 'power', value: 10 },
    effectId: 'LOOT_QUANTITY_BOOST',
    effectDescription: 'Increases Loot Quantity',
    effectDescriptionKo: '전리품 획득량 증가',
  },
  relic_leviathan_mirror: {
    id: 'relic_leviathan_mirror',
    name: "Leviathan's Deceptive Mirror",
    nameKo: '레비아탄의 뒤틀린 투영',
    type: 'stackable',
    image: 'LeviathanMirrorRelic',
    description: 'Increases damage/mining speed based on missing HP.',
    descriptionKo: '잃은 체력에 비례하여 위력이 강화됩니다.',
    bonus: { stat: 'defense', value: 5 },
    effectId: 'TWISTED_PROJECTION',
    effectDescription: 'Enhances Berserk Effect',
    effectDescriptionKo: '광전사 효과 강화',
  },
  relic_lucifer_ice: {
    id: 'relic_lucifer_ice',
    name: "Lucifer's Eternal Ice",
    nameKo: '루시퍼의 영겁 서리',
    type: 'stackable',
    image: 'LuciferIceRelic',
    description: 'Increases all stats for every 100m reached.',
    descriptionKo: '깊이 도달에 따른 보너스가 중첩 강화됩니다.',
    bonus: { stat: 'maxHp', value: 50 },
    effectId: 'INFINITE_SCALING',
    effectDescription: 'Enhances Infinite Growth Effect',
    effectDescriptionKo: '무한 성장 효과 강화',
  },
};
