import { Drill } from '../types/game';

export const DRILLS: { [id: string]: Drill } = {
  rusty_drill: {
    id: 'rusty_drill',
    name: 'Rusty Drill',
    description: 'A basic, reliable drill. Nothing fancy.',
    icon: '🪛',
    basePower: 15,
    cooldownMs: 150,
    price: { dirt: 0 }, // Free / Default
  },
  stone_drill: {
    id: 'stone_drill',
    name: 'Stone Drill',
    description: 'A sturdy drill made of reinforced rock.',
    icon: '🪨',
    basePower: 40,
    cooldownMs: 160,
    price: { stone: 10 },
  },
  iron_drill: {
    id: 'iron_drill',
    name: 'Iron Drill',
    description: 'Sharpened iron tip for consistent power.',
    icon: '🥈',
    basePower: 90,
    cooldownMs: 200,
    price: { iron: 20, coal: 30 },
  },
  gold_drill: {
    id: 'gold_drill',
    name: 'Gold Drill',
    description: 'Flashy but hard as a rock.',
    icon: '🥇',
    basePower: 240,
    cooldownMs: 240,
    price: { gold: 20, iron: 30 },
  },
  diamond_drill: {
    id: 'diamond_drill',
    name: 'Diamond Drill',
    description: 'Industrial grade diamond tip.',
    icon: '💎',
    basePower: 600,
    cooldownMs: 280,
    price: { diamond: 20, gold: 30 },
  },
  coal_drill: {
    id: 'coal_drill',
    name: 'Coal-Powered Drill',
    description: 'Turns coal into extra torque.',
    icon: '🔥',
    basePower: 400,
    cooldownMs: 280,
    price: { coal: 50, iron: 50 },
  },
  emerald_drill: {
    id: 'emerald_drill',
    name: 'Emerald Drill',
    description: 'Highly efficient emerald-tipped drill.',
    icon: '💚',
    basePower: 3500,
    cooldownMs: 600,
    specialEffect: 'efficient',
    price: { emerald: 30, diamond: 50 },
  },
  ruby_drill: {
    id: 'ruby_drill',
    name: 'Ruby Drill',
    description: 'Hardened ruby for intense drilling.',
    icon: '❤️',
    basePower: 9000,
    cooldownMs: 500,
    price: { ruby: 30, emerald: 50 },
  },
  sapphire_drill: {
    id: 'sapphire_drill',
    name: 'Sapphire Drill',
    description: 'Precision sapphire tip for fast deep mining.',
    icon: '💙',
    basePower: 22000,
    cooldownMs: 400,
    price: { sapphire: 30, ruby: 50 },
  },
  uranium_drill: {
    id: 'uranium_drill',
    name: 'Uranium Drill',
    description: 'Unstable power that creates micro-explosions.',
    icon: '☢️',
    basePower: 60000,
    cooldownMs: 800,
    specialEffect: 'explosive',
    price: { uranium: 30, sapphire: 50 },
  },
  obsidian_drill: {
    id: 'obsidian_drill',
    name: 'Obsidian Drill',
    description: 'Ultimate drill made from volcanic glass.',
    icon: '🖤',
    basePower: 150000,
    cooldownMs: 600,
    price: { obsidian: 30, uranium: 50 },
  },
  sonic_drill: {
    id: 'sonic_drill',
    name: 'Sonic Drill',
    description: 'Vibrates at high frequencies for rapid drilling.',
    icon: '🔊',
    basePower: 2500,
    cooldownMs: 100,
    specialEffect: 'speed',
    price: { sapphire: 100, iron: 200 },
  },
};
