import { MineralDefinition } from './types';
import {
  UNRELEASED_CIRCLE_MINERAL_DEFENSE,
  UNRELEASED_CIRCLE_MINERAL_HEALTH,
} from '../lateCircleLock';

export const circle8Minerals: MineralDefinition[] = [
  {
    key: 'mimicite',
    name: 'Mimicite',
    nameKo: '의태석',
    referenceName: 'Labradorite',
    referenceNameKo: '라브라도라이트',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '제8원 사기의 층에서 발견되는 기만적인 광물입니다.',
    color: '#94a3b8',
    minDepth: 2110,
    basePrice: 320,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'lurerstone',
    name: 'Lurerstone',
    nameKo: '기만석',
    referenceName: 'Opal',
    referenceNameKo: '오팔',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '환각을 일으켜 탐험가를 유혹하는 광물입니다.',
    color: '#94a3b8',
    minDepth: 2210,
    basePrice: 640,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'phantomite',
    name: 'Phantomite',
    nameKo: '망령석',
    referenceName: 'Moonstone',
    referenceNameKo: '월장석',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '실체가 없는 듯 흐릿하게 빛나는 신비한 광물입니다.',
    color: '#94a3b8',
    minDepth: 2310,
    basePrice: 960,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
