import { MineralDefinition } from './types';

export const circle3Minerals: MineralDefinition[] = [
  {
    key: 'moldstone',
    name: 'Moldstone',
    nameKo: '곰팡석',
    referenceName: 'Malachite',
    referenceNameKo: '공작석',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '제3원 탐식의 층에서 발견되는 부패한 광물입니다.',
    color: '#94a3b8',
    minDepth: 610,
    basePrice: 12,
    baseHealth: 400,
    defense: 50,
    image: 'MoldStoneIcon',
    tileImage: 'MoldStoneTile',
  },
  {
    key: 'sludgestone',
    name: 'Sludgestone',
    nameKo: '오물석',
    referenceName: 'Bitumen',
    referenceNameKo: '역청',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '진흙과 오물이 섞여 굳어진 광물입니다.',
    color: '#94a3b8',
    minDepth: 710,
    basePrice: 24,
    baseHealth: 700,
    defense: 60,
    image: 'SludgeStoneIcon',
    tileImage: 'SludgeStoneTile',
  },
  {
    key: 'rotstone',
    name: 'Rotstone',
    nameKo: '부패석',
    referenceName: 'Sulfur',
    referenceNameKo: '유황',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '썩은 기운이 깊게 스며든 부패한 광물입니다.',
    color: '#94a3b8',
    minDepth: 810,
    basePrice: 36,
    baseHealth: 1000,
    defense: 70,
    image: 'RotStoneIcon',
    tileImage: 'RotStoneTile',
  },
];
