import { MineralDefinition } from './types';

export const circle3Minerals: MineralDefinition[] = [
  {
    key: 'moldstone',
    name: 'Moldstone',
    nameKo: '곰팡석',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '제3원 탐식의 층에서 발견되는 부패한 광물입니다.',
    color: '#94a3b8',
    minDepth: 610,
    basePrice: 10,
    baseHealth: 250,
    defense: 30,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'sludgestone',
    name: 'Sludgestone',
    nameKo: '오물석',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '진흙과 오물이 섞여 굳어진 광물입니다.',
    color: '#94a3b8',
    minDepth: 710,
    basePrice: 20,
    baseHealth: 500,
    defense: 35,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'rotstone',
    name: 'Rotstone',
    nameKo: '부패석',
    icon: '💎',
    description: 'Mineral from Circle 3 - Gluttony',
    descriptionKo: '썩은 기운이 깊게 스며든 부패한 광물입니다.',
    color: '#94a3b8',
    minDepth: 810,
    basePrice: 30,
    baseHealth: 750,
    defense: 40,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
