import { MineralDefinition } from './types';
import {
  UNRELEASED_CIRCLE_MINERAL_DEFENSE,
  UNRELEASED_CIRCLE_MINERAL_HEALTH,
} from '../lateCircleLock';

export const circle7Minerals: MineralDefinition[] = [
  {
    key: 'thornstone',
    name: 'Thornstone',
    nameKo: '가시석',
    referenceName: 'Stibnite',
    referenceNameKo: '휘안석',
    icon: '💎',
    description: 'Mineral from Circle 7 - Violence',
    descriptionKo: '제7원 폭력의 층에서 발견되는 날카로운 광물입니다.',
    color: '#94a3b8',
    minDepth: 1810,
    basePrice: 160,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'bloodstone',
    name: 'Bloodstone',
    nameKo: '혈석',
    referenceName: 'Bloodstone',
    referenceNameKo: '혈석',
    icon: '💎',
    description: 'Mineral from Circle 7 - Violence',
    descriptionKo: '피가 응고된 듯한 짙은 붉은색의 광물입니다.',
    color: '#94a3b8',
    minDepth: 1910,
    basePrice: 320,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'cruelite',
    name: 'Cruelite',
    nameKo: '잔혹석',
    referenceName: 'Cinnabar',
    referenceNameKo: '진사석',
    icon: '💎',
    description: 'Mineral from Circle 7 - Violence',
    descriptionKo: '차갑고 무자비한 기운을 내뿜는 단단한 광물입니다.',
    color: '#94a3b8',
    minDepth: 2010,
    basePrice: 480,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
