import { MineralDefinition } from './types';

export const circle5Minerals: MineralDefinition[] = [
  {
    key: 'ragestone',
    name: 'Ragestone',
    nameKo: '분노석',
    icon: '💎',
    description: 'Mineral from Circle 5 - Wrath',
    descriptionKo: '제5원 분노의 층에서 발견되는 뜨거운 광물입니다.',
    color: '#94a3b8',
    minDepth: 1210,
    basePrice: 40,
    baseHealth: 1562,
    defense: 50,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'cinderstone',
    name: 'Cinderstone',
    nameKo: '잿빛석',
    icon: '💎',
    description: 'Mineral from Circle 5 - Wrath',
    descriptionKo: '타버린 재가 뭉쳐진 듯한 거친 광물입니다.',
    color: '#94a3b8',
    minDepth: 1310,
    basePrice: 80,
    baseHealth: 3125,
    defense: 55,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'furystone',
    name: 'Furystone',
    nameKo: '격노석',
    icon: '💎',
    description: 'Mineral from Circle 5 - Wrath',
    descriptionKo: '폭발적인 에너지를 머금고 있는 광물입니다.',
    color: '#94a3b8',
    minDepth: 1410,
    basePrice: 120,
    baseHealth: 4687,
    defense: 60,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
