import { MineralDefinition } from './types';

export const circle4Minerals: MineralDefinition[] = [
  {
    key: 'goldstone',
    name: 'Goldstone',
    nameKo: '사금석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '제4원 탐심의 층에서 발견되는 빛나는 광물입니다.',
    color: '#94a3b8',
    minDepth: 910,
    basePrice: 20,
    baseHealth: 625,
    defense: 40,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'luststone',
    name: 'Luststone',
    nameKo: '욕망석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '보는 이의 소유욕을 자극하는 아름다운 광물입니다.',
    color: '#94a3b8',
    minDepth: 1010,
    basePrice: 40,
    baseHealth: 1250,
    defense: 45,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'midasite',
    name: 'Midasite',
    nameKo: '미다스석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '닿는 모든 것을 황금으로 바꿀 듯한 광채를 냅니다.',
    color: '#94a3b8',
    minDepth: 1110,
    basePrice: 60,
    baseHealth: 1875,
    defense: 50,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
