import { MineralDefinition } from './types';

export const circle4Minerals: MineralDefinition[] = [
  {
    key: 'goldstone',
    name: 'Goldstone',
    nameKo: '사금석',
    referenceName: 'Native Gold',
    referenceNameKo: '자연금',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '제4원 탐심의 층에서 발견되는 빛나는 광물입니다.',
    color: '#d8a02a',
    minDepth: 910,
    basePrice: 20,
    baseHealth: 1700,
    defense: 100,
    image: 'GoldStoneIcon',
    tileImage: 'GoldStoneTile',
  },
  {
    key: 'luststone',
    name: 'Luststone',
    nameKo: '욕망석',
    referenceName: 'Pyrite',
    referenceNameKo: '황철석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '보는 이의 소유욕을 자극하는 아름다운 광물입니다.',
    color: '#d9892e',
    minDepth: 1010,
    basePrice: 40,
    baseHealth: 2450,
    defense: 120,
    image: 'LustStoneIcon',
    tileImage: 'LustStoneTile',
  },
  {
    key: 'midasite',
    name: 'Midasite',
    nameKo: '미다스석',
    referenceName: 'Chalcopyrite',
    referenceNameKo: '황동석',
    icon: '💎',
    description: 'Mineral from Circle 4 - Greed',
    descriptionKo: '닿는 모든 것을 황금으로 바꿀 듯한 광채를 냅니다.',
    color: '#f0c14b',
    minDepth: 1110,
    basePrice: 60,
    baseHealth: 3200,
    defense: 150,
    image: 'MidasiteIcon',
    tileImage: 'MidasiteTile',
  },
];
