import { MineralDefinition } from './types';
import {
  UNRELEASED_CIRCLE_MINERAL_DEFENSE,
  UNRELEASED_CIRCLE_MINERAL_HEALTH,
} from '../lateCircleLock';

export const circle9Minerals: MineralDefinition[] = [
  {
    key: 'froststone',
    name: 'Froststone',
    nameKo: '서리석',
    referenceName: 'Cryolite',
    referenceNameKo: '빙정석',
    icon: '💎',
    description: 'Mineral from Circle 9 - Treachery',
    descriptionKo: '제9원 배신의 층에서 발견되는 얼어붙은 광물입니다.',
    color: '#94a3b8',
    minDepth: 2410,
    basePrice: 640,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'glacialite',
    name: 'Glacialite',
    nameKo: '빙하석',
    referenceName: 'Kyanite',
    referenceNameKo: '남정석',
    icon: '💎',
    description: 'Mineral from Circle 9 - Treachery',
    descriptionKo: '수만 년간의 냉기를 품고 있는 전설적인 광물입니다.',
    color: '#94a3b8',
    minDepth: 2510,
    basePrice: 1280,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'abyssstone',
    name: 'Abyssstone',
    nameKo: '심연석',
    referenceName: 'Morion',
    referenceNameKo: '흑수정',
    icon: '💎',
    description: 'Mineral from Circle 9 - Treachery',
    descriptionKo: '지옥의 가장 깊은 곳, 절대적인 어둠을 상징하는 광물입니다.',
    color: '#94a3b8',
    minDepth: 2610,
    basePrice: 1920,
    baseHealth: UNRELEASED_CIRCLE_MINERAL_HEALTH,
    defense: UNRELEASED_CIRCLE_MINERAL_DEFENSE,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
