import { MineralDefinition } from './types';

export const circle2Minerals: MineralDefinition[] = [
  {
    key: 'crimsonstone',
    name: 'Crimsonstone',
    nameKo: '핏빛석',
    icon: '💎',
    description: 'Mineral from Circle 2 - Lust',
    descriptionKo: '제2원 색욕의 층에서 발견되는 핏빛 광물입니다.',
    color: '#94a3b8',
    minDepth: 0,
    basePrice: 5,
    baseHealth: 30,
    defense: 2,
    image: 'CrimsonStoneIcon',
    tileImage: 'CrimsonStoneTile',
  },
  {
    key: 'galestone',
    name: 'Galestone',
    nameKo: '돌풍석',
    icon: '💎',
    description: 'Mineral from Circle 2 - Lust',
    descriptionKo: '강한 바람의 기운이 깃든 광물입니다.',
    color: '#94a3b8',
    minDepth: 100,
    basePrice: 10,
    baseHealth: 60,
    defense: 5,
    image: 'GaleStoneIcon',
    tileImage: 'GaleStoneTile',
  },
  {
    key: 'fervorstone',
    name: 'Fervorstone',
    nameKo: '열정석',
    icon: '💎',
    description: 'Mineral from Circle 2 - Lust',
    descriptionKo: '뜨거운 열망이 느껴지는 단단한 광물입니다.',
    color: '#94a3b8',
    minDepth: 200,
    basePrice: 15,
    baseHealth: 120,
    defense: 8,
    image: 'FervorStoneIcon',
    tileImage: 'FervorStoneTile',
  },
];
