import { MineralDefinition } from './types';

export const circle8Minerals: MineralDefinition[] = [
  {
    key: 'mimicite',
    name: 'Mimicite',
    nameKo: '의태석',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '제8원 사기의 층에서 발견되는 기만적인 광물입니다.',
    color: '#94a3b8',
    minDepth: 2110,
    basePrice: 320,
    baseHealth: 24414,
    defense: 80,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'lurerstone',
    name: 'Lurerstone',
    nameKo: '기만석',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '환각을 일으켜 탐험가를 유혹하는 광물입니다.',
    color: '#94a3b8',
    minDepth: 2210,
    basePrice: 640,
    baseHealth: 48828,
    defense: 85,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'phantomite',
    name: 'Phantomite',
    nameKo: '망령석',
    icon: '💎',
    description: 'Mineral from Circle 8 - Fraud',
    descriptionKo: '실체가 없는 듯 흐릿하게 빛나는 신비한 광물입니다.',
    color: '#94a3b8',
    minDepth: 2310,
    basePrice: 960,
    baseHealth: 73242,
    defense: 90,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
