import { MineralDefinition } from './types';

export const circle6Minerals: MineralDefinition[] = [
  {
    key: 'ashstone',
    name: 'Ashstone',
    nameKo: '낙진석',
    icon: '💎',
    description: 'Mineral from Circle 6 - Heresy',
    descriptionKo: '제6원 이단의 층에서 발견되는 메마른 광물입니다.',
    color: '#94a3b8',
    minDepth: 1510,
    basePrice: 80,
    baseHealth: 3906,
    defense: 60,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'blightstone',
    name: 'Blightstone',
    nameKo: '저주석',
    icon: '💎',
    description: 'Mineral from Circle 6 - Heresy',
    descriptionKo: '불길한 원한이 느껴지는 어두운 광물입니다.',
    color: '#94a3b8',
    minDepth: 1610,
    basePrice: 160,
    baseHealth: 7812,
    defense: 65,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
  {
    key: 'vexite',
    name: 'Vexite',
    nameKo: '고뇌석',
    icon: '💎',
    description: 'Mineral from Circle 6 - Heresy',
    descriptionKo: '파낼수록 알 수 없는 고통이 전해지는 광물입니다.',
    color: '#94a3b8',
    minDepth: 1710,
    basePrice: 240,
    baseHealth: 11718,
    defense: 70,
    image: 'GoldIcon',
    tileImage: 'StoneTile',
  },
];
