import { MineralDefinition } from './types';

export const stoneMinerals: MineralDefinition[] = [
  {
    key: 'stone',
    name: 'Stone',
    nameKo: '돌',
    icon: '🪨',
    description: 'Common background stone. Found throughout all circles.',
    descriptionKo: '모든 서클에서 발견되는 일반 배경 돌입니다.',
    color: '#9ca3af',
    minDepth: 0,
    basePrice: 0,
    baseHealth: 20,
    defense: 0,
    collectible: false,
    image: null,
    tileImage: 'StoneTile',
  },
  {
    key: 'gluttony_stone',
    name: 'Gluttony Stratum',
    nameKo: '탐식 지층',
    icon: '🪨',
    description: 'Circle 3 background stratum. It yields no collectible mineral.',
    descriptionKo: '제3원 탐식의 일반 배경 지층입니다. 수집 가능한 광물을 드롭하지 않습니다.',
    color: '#4b5248',
    minDepth: 300,
    basePrice: 0,
    baseHealth: 200,
    defense: 0,
    collectible: false,
    image: null,
    tileImage: 'C3Tile',
  },
  {
    key: 'greed_stone',
    name: 'Greed Stratum',
    nameKo: '탐욕 지층',
    icon: '🪨',
    description: 'Circle 4 background stratum. It yields no collectible mineral.',
    descriptionKo: '제4원 탐욕의 일반 배경 지층입니다. 수집 가능한 광물을 드롭하지 않습니다.',
    color: '#4a371e',
    minDepth: 600,
    basePrice: 0,
    baseHealth: 320,
    defense: 0,
    collectible: false,
    image: null,
    tileImage: 'C4Tile',
  },
];
