// [자동 생성됨] 이 파일은 scripts/generateAtlasMap.js 스크립트에 의해 생성되었습니다.
// 에셋이 추가되면 이 파일이 자동으로 업데이트됩니다.

export const ATLAS_FILE_MAPPING = {
  Asmodeus: 'Asmodeus.png',
  AsmodeusRingRelic: 'AsmodeusRingRelic.png',
  AttackRune: 'AttackRune.png',
  BaseTileset: 'BaseTileset.png',
  BloatedDevourer: 'BloatedDevourer.png',
  BookIcon: 'BookIcon.webp',
  Cerberus: 'Cerberus.png',
  CrimsonFangDrill: 'CrimsonFangDrill.png',
  CrimsonPlateArmor: 'CrimsonPlateArmor.png',
  CrimsonStoneIcon: 'CrimsonStoneIcon.png',
  CrimsonStoneTile: 'CrimsonStoneTile.png',
  CrimsonStrideBoots: 'CrimsonStrideBoots.png',
  CrimsonVeilHelmet: 'CrimsonVeilHelmet.png',
  CritDmgRune: 'CritDmgRune.png',
  CritRateRune: 'CritRateRune.png',
  FervorStoneIcon: 'FervorStoneIcon.png',
  FervorStoneTile: 'FervorStoneTile.png',
  FireBall: 'FireBall.png',
  FraudEssence: 'FraudEssence.png',
  GaleBat: 'GaleBat.png',
  GaleStoneIcon: 'GaleStoneIcon.png',
  GaleStoneTile: 'GaleStoneTile.png',
  GluttoyEssence: 'GluttoyEssence.png',
  GoldIcon: 'MoneyIcon.webp',
  GreedEssence: 'GreedEssence.png',
  HeresyEssence: 'HeresyEssence.png',
  InventoryIcon: 'InventoryIcon.webp',
  LuckRune: 'LuckRune.png',
  LustEssence: 'LustEssence.png',
  LustfulWhisperer: 'LustfulWhisperer.png',
  Mechanic: 'Mechanic.png',
  Merchant: 'Merchant.png',
  MiningSpeedRune: 'MiningSpeedRune.png',
  MoldstoneIcon: 'MoldstoneIcon.png',
  MoldstoneTile: 'MoldstoneTile.png',
  MoveSpeedRune: 'MoveSpeedRune.png',
  Player: 'Player.png',
  PlayerWalkDown01: 'PlayerWalkDown01.png',
  PlayerWalkDown02: 'PlayerWalkDown02.png',
  PlayerWalkDown03: 'PlayerWalkDown03.png',
  PlayerWalkDown04: 'PlayerWalkDown04.png',
  PlayerWalkDown05: 'PlayerWalkDown05.png',
  PlayerWalkDown06: 'PlayerWalkDown06.png',
  PlayerWalkLeft01: 'PlayerWalkLeft01.png',
  PlayerWalkLeft02: 'PlayerWalkLeft02.png',
  PlayerWalkLeft03: 'PlayerWalkLeft03.png',
  PlayerWalkLeft04: 'PlayerWalkLeft04.png',
  PlayerWalkLeft05: 'PlayerWalkLeft05.png',
  PlayerWalkLeft06: 'PlayerWalkLeft06.png',
  PlayerWalkUp01: 'PlayerWalkUp01.png',
  PlayerWalkUp02: 'PlayerWalkUp02.png',
  PlayerWalkUp03: 'PlayerWalkUp03.png',
  PlayerWalkUp04: 'PlayerWalkUp04.png',
  PlayerWalkUp05: 'PlayerWalkUp05.png',
  PlayerWalkUp06: 'PlayerWalkUp06.png',
  SettingsIcon: 'SettingsIcon.webp',
  StatusIcon: 'StatusIcon.webp',
  StoneTile: 'StoneTile.png',
  TreacheryEssence: 'TreacheryEssence.png',
  ViolenceEssence: 'ViolenceEssence.png',
  WindTornSoul: 'WindTornSoul.png',
  WrathEssence: 'WrathEssence.png',
} as const;

export type AtlasIconName = keyof typeof ATLAS_FILE_MAPPING;
