// [자동 생성됨] 이 파일은 scripts/generateAtlasMap.js 스크립트에 의해 생성되었습니다.
// 에셋이 추가되면 이 파일이 자동으로 업데이트됩니다.

export const ATLAS_FILE_MAPPING = {
  Asmodeus: 'Asmodeus.png',
  AsmodeusRingRelic: 'AsmodeusRingRelic.png',
  AttackRune: 'AttackRune.png',
  BaseTileset: 'BaseTileset.png',
  BloatedDevourer: 'BloatedDevourer.png',
  BookIcon: 'BookIcon.webp',
  BossCoreTile: 'boss_core.png',
  BossSkinTile: 'boss_skin.png',
  Cerberus: 'Cerberus.png',
  CrimsonFangDrill: 'CrimsonFangDrill.png',
  CrimsonPlateArmor: 'CrimsonPlateArmor.png',
  CrimsonStoneIcon: 'CrimsonStoneIcon.png',
  CrimsonStoneTile: 'CrimsonStoneTile.png',
  CrimsonStrideBoots: 'CrimsonStrideBoots.png',
  CrimsonVeilHelmet: 'CrimsonVeilHelmet.png',
  CritDmgRune: 'CritDmgRune.png',
  CritRateRune: 'CritRateRune.png',
  DirtTile: 'DirtTile.png',
  FervorStoneIcon: 'FervorStoneIcon.png',
  FervorStoneTile: 'FervorStoneTile.png',
  FireBall: 'FireBall.png',
  FraudEssence: 'FraudEssence.png',
  GaleBat: 'GaleBat.png',
  GaleStoneIcon: 'GaleStoneIcon.png',
  GaleStoneTile: 'GaleStoneTile.png',
  GluttoyEssence: 'GluttoyEssence.png',
  GoldIcon: 'MoneyIcon.webp',
  GreedEssence: 'GreedEssence.png',
  HeresyEssence: 'HeresyEssence.png',
  InventoryIcon: 'InventoryIcon.webp',
  LuckRune: 'LuckRune.png',
  LustEssence: 'LustEssence.png',
  LustfulWhisperer: 'LustfulWhisperer.png',
  Mechanic: 'Mechanic.png',
  Merchant: 'Merchant.png',
  MiningSpeedRune: 'MiningSpeedRune.png',
  MoveSpeedRune: 'MoveSpeedRune.png',
  Player: 'Player.png',
  SettingsIcon: 'SettingsIcon.webp',
  StatusIcon: 'StatusIcon.webp',
  StoneTile: 'StoneTile.png',
  TreacheryEssence: 'TreacheryEssence.png',
  ViolenceEssence: 'ViolenceEssence.png',
  WindTornSoul: 'WindTornSoul.png',
  WrathEssence: 'WrathEssence.png',
} as const;

export type AtlasIconName = keyof typeof ATLAS_FILE_MAPPING;
