import { SkillRune } from '../types/game';

/**
 * 룬(Rune) 시스템의 기반 명세를 정의합니다.
 */
export const SKILL_RUNES: Record<string, SkillRune> = {
  attack_rune: {
    id: 'attack_rune',
    name: 'Attack Rune',
    nameKo: '공격의 룬',
    description: 'Increases Base Power',
    descriptionKo: '기본 위력을 증가시킵니다.',
    effectType: 'passive',
    rarity: 'Common',
    powerBonus: 10,
    image: 'AttackRune',
  },
  speed_rune: {
    id: 'speed_rune',
    name: 'Mining Speed Rune',
    nameKo: '채굴 속도의 룬',
    description: 'Increases Mining Speed',
    descriptionKo: '채굴 속도를 증가시킵니다.',
    effectType: 'passive',
    rarity: 'Common',
    speedMult: 0.05,
    image: 'MiningSpeedRune',
  },
  move_speed_rune: {
    id: 'move_speed_rune',
    name: 'Movement Speed Rune',
    nameKo: '이동 속도의 룬',
    description: 'Increases Movement Speed',
    descriptionKo: '이동 속도를 증가시킵니다.',
    effectType: 'passive',
    rarity: 'Common',
    effectValue: 0.05,
    image: 'MoveSpeedRune',
  },
  luck_rune: {
    id: 'luck_rune',
    name: 'Luck Rune',
    nameKo: '행운의 룬',
    description: 'Increases Double Drop Chance',
    descriptionKo: '추가 드롭 확률을 증가시킵니다.',
    effectType: 'passive',
    rarity: 'Common',
    effectValue: 0.05,
    image: 'LuckRune',
  },
  crit_rate_rune: {
    id: 'crit_rate_rune',
    name: 'Acuity Rune',
    nameKo: '기민함의 룬',
    description: 'Sharpens perception to pierce weak points, increasing Critical Hit Chance',
    descriptionKo: '약점을 꿰뚫는 기민함으로 치명타 확률을 높입니다.',
    effectType: 'passive',
    rarity: 'Common',
    effectChance: 0.05,
    image: 'CritRateRune',
  },
  crit_dmg_rune: {
    id: 'crit_dmg_rune',
    name: 'Severity Rune',
    nameKo: '가혹함의 룬',
    description: "Hones the blade's edge to cut deeper, increasing Critical Hit Damage",
    descriptionKo: "심도 깊은 가혹함으로 치명타 피해량을 높입니다.",
    effectType: 'passive',
    rarity: 'Common',
    effectValue: 0.2,
    image: 'CritDmgRune',
  },
};
